name: MagiaPrro
main: org.magiaperro.main.Main
version: 1.0
api-version: 1.13
commands:
  example:
    description: Un comando de ejemplo
    usage: /example
  backpack:
    description: Mochila
    usage: /backpack
  givecustom:
    description: Obtener un objeto custom
    usage: /givecustom <numero>
    parameters:
      numero:
        description: ID del objeto
        type: integer
        required: true